apiVersion: ENC[AES256_GCM,data:a9E=,iv:cXoJxpiMFpVAKLSY1W+ZZnZqKHqrSJ+xNMceOsSgjq4=,tag:YNcimtif1lJfUVX4gm//9A==,type:str]
kind: ENC[AES256_GCM,data:DSQ2wf1W,iv:n8YA+hApSXjrYiT4cCAn4snt0nz39oT3E1dN3r/NeR4=,tag:GySvi0hOlDj/RxjfLgg/iA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:bMAH4UXnKm699d00NSVCZrA=,iv:m22Yc1p8WbgQCLzOh01yqeHXChWYLHnFQTDepoboOwA=,tag:TYePPJwK2vgFXRRN7WXHhQ==,type:str]
    namespace: ENC[AES256_GCM,data:jqAEtZmLgcM=,iv:khS108JUBT/DqN97RpBy8IiM5nBZ83oFlpQe1tlv0L8=,tag:KS/ePhiwsQYVG/7W8hXhZg==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:eQW6maIWH5swlg==,iv:Z61WWlnDTSYwpxwzhOCMr04Q8Im4+1zAhY4HiFtQkP0=,tag:dcbFh9rHvOrrQP7gwXUHkg==,type:str]
type: ENC[AES256_GCM,data:SJD5QUAx,iv:Ygg1dptYPN8BxbRGm9Q7rMcGbllVI70facXYpefJ3lI=,tag:Q+Ln/ZgnBk7UZMBt+V1s3g==,type:str]
stringData:
    postgresql-password: ENC[AES256_GCM,data:uuk2Uc9AlV3FBBp80+N+Q0fc,iv:vb0YqOmaBDKA8CpPVcYcaYxl5KZnM/NQXPMlRWtiyaw=,tag:yjNNcB+8hDrXD3PO2M3PBQ==,type:str]
sops:
    age:
        - recipient: age1f45e4rjg4f0ptw0q63t5nynsq7lcnc055fyxf5st23hlqu3ft9wqcgkmun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVnBvU2xRai8zRlVuRDc4
            dHJPMzllcjBtUlBxUk43RUdJbmIrTUhxS0hNCnpnQjlkekNieVZtQUJPcmd1UVg5
            cEsxZHloWk9KdXN6ZkFSNHVZNy90Q1UKLS0tIGdXYllQZHh3cFZJcmF6NmE4NWVL
            VnhpTDhISVNvTXJxUTFianNPUDZlMTgKGzwjbjtInzdqmIcy2CxrYNqqku/KeOoZ
            RajjrmtAnejiPENvDvVDsvJCqXkjBslMb8rhX9dB9pJ4zXGauolXwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T17:16:50Z"
    mac: ENC[AES256_GCM,data:pk2qFRT/pnu/2Z6DLcI9kXgEK74yLeh8mA7+BjjakObBEjwFoWEWKZx3LGhB0PFPyGqxrB+o4ovAjVTC2O0K9jtBEZN9DncZfCtacxBIcrufYEVXHAVudRKSzqXIWfyvKJIL8sVqpyV/7tcuKeEHChiLrNcvd8H41hKIaX8bxYA=,iv:nUhPHwM6l6/S2Pvw4AHeIlJUU4NfEeF/YDo4g1OU6Ds=,tag:odqHzR0frMkqzaqembpjMQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
