apiVersion: v1
kind: Secret
metadata:
    name: postgresql-secret
    namespace: pipeline
    labels:
        app.kubernetes.io/name: postgresql
type: Opaque
stringData:
    postgresql-password: ENC[AES256_GCM,data:XH/I4wImetpH4JCD/o2JegAu,iv:xwbURqbHl1vWqNlQ997tokgRX8mOqzRfrMBjkSym4zc=,tag:tfA7sRLJzCW5HAxyefrNkQ==,type:str]
sops:
    age:
        - recipient: age1f45e4rjg4f0ptw0q63t5nynsq7lcnc055fyxf5st23hlqu3ft9wqcgkmun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwME96SysxejIxUDloZjBM
            WW5ZZG5rQVRyVE14VTVpWUVna3YxRjJBazBFCis2V3lreU93RlRoUUdTMzV3MUJB
            aEIvQ2hCc3hDT3dLcVhiQ1M5cyt1Q1UKLS0tIFp2Rmc2ZnFLYjBNMStSa0lyNlkw
            a2o2OEp4Q29GS29TbXRSK1kvZmhkOW8KUV1iOy+uL/W0hs39cSNg3utYsyBXFN7f
            iqf4WwAMh0tCgQxi4lM2ScHk1/OkJmavWHyeZWnw7SF48Yicnzf+zQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T04:18:48Z"
    mac: ENC[AES256_GCM,data:CZ34YgKgaMTPjuJ8ltBAIg0Xe296ZXUqg+j95363JV6lcXnx5Q666jZrQep6gB8BHPEJD1j0EuOkt6kXTwC4l7wj8bFgEOHe4ud3eniDoje0SwdAb2lInZFCDFkv2oWTRGIiGcMJoRM9H4LKFF6ftXl9GTk2b8RvCf4bXmeuJKY=,iv:j2Ra5kFD8Q3mtMi74ITMr434L7VvaxcmiiQnKtgAPCo=,tag:8PEwLB6PhhSMHwH99uke3Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
