apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-api
  labels:
    app: pipeline-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline-api
  template:
    metadata:
      labels:
        app: pipeline-api
    spec:
      serviceAccountName: pipeline-api
      containers:
        - name: pipeline-api
          image: tiwari91/pipeline-api:latest
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: pipeline-config
            - secretRef:
                name: pipeline-secrets
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 5
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 20
