apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pipeline-api
  labels:
    app: pipeline-api
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: pipeline-api
