apiVersion: v1
kind: Secret
metadata:
    name: pipeline-secrets
    labels:
        app: pipeline-api
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:InQYmvYylgosloknx/+Dg/6+,iv:anxhl8lHGqs4oJLbIhzZhtpIqlHtPx84Qqbqbb4pU4Y=,tag:5V0S8ZxVqWOO8LJP1eGmPQ==,type:str]
sops:
    age:
        - recipient: age1f45e4rjg4f0ptw0q63t5nynsq7lcnc055fyxf5st23hlqu3ft9wqcgkmun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVW51NXJxcWl0ZnU2Mkhr
            cmRMRDBGOEx6RVpZWk1mNk4xbnh2ZGp0aTE0CndpR0F4WnMvQ01kMDUwQmhtaVl3
            cUhzK0FORUhHYTdycnRMNWZsbWRvR3MKLS0tIFliUjZKR2VmUFp3WDd1UkI2SWt4
            VGZJemRJbHBrOVMza0ExdElsWmtCaGMKd9f0HWNOo6540cUpI2Qb9oExM+CMG5Ux
            ruLBRj0zYcaDNTHs2js1syQvg1z0UHlJo98sr2r/aXi3QEWsVQ0YAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T04:18:48Z"
    mac: ENC[AES256_GCM,data:/twVF0AujGyqECvmj6SSCoPVWD5AR78n4+TzK0eZ/T5ecoL5DsZ1cdgQiHyeEsCkurpQVMtjOEwdfgS4F67bvi6496JtGVagDtv7FPPXDm8iRgBWf60pB6jCvPXDGu4Zf9LqJLP/VOinBZweM6I7N8Ok2YkLUyyeh5jYp7PCxKI=,iv:ktV0mGbRuVcIzCO7K+opbS+H1qsSqW+In/YjyZcej8c=,tag:4bDyMQV7nEF0wMcCtPsZfw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
