apiVersion: ENC[AES256_GCM,data:xEU=,iv:lkwr+xHwDqD0TUd8E8D+oacfNkOD4DM5rXJFFbJ3HvI=,tag:7XrY4lLrEDMcq9Pen4GklA==,type:str]
kind: ENC[AES256_GCM,data:/+suBx1t,iv:MA7T9GkuRaCT5la6u34y9RsdWp5p2BKqfDcCrXEgUvs=,tag:3zZxhwJaEk3UMYxe9ivH2A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qBv3TnxbJIx41/808jjRug==,iv:ml2QSy+fxB6KdCcd4Uj76ofk6zgNFEsKf/7j3vz0peE=,tag:DI2aj01K0YlefirOiTy46w==,type:str]
    labels:
        app: ENC[AES256_GCM,data:NvkSz24CGU0DfWbT,iv:wBG7Tn9UR17M4SNSQAy8YXWi0oH7osr7iICUm3SBoOc=,tag:GVje/Wb8mRkCcXX2NlociQ==,type:str]
type: ENC[AES256_GCM,data:Gqip8vUD,iv:tYd0ODKMfqIL5HIfHqtY079mQ9M48ztHSnPDNPiMdhk=,tag:/F9rP81/3WBDHfeJ+UZrrA==,type:str]
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:5bP0knNH0qOfkJWPOxQXvA4T,iv:8aHxbMVrImy01otOtUdvT2wJOh5KS2nrEMWUhJ+0xto=,tag:OYZCMLNkvOlXPB66ziIjKw==,type:str]
sops:
    age:
        - recipient: age1f45e4rjg4f0ptw0q63t5nynsq7lcnc055fyxf5st23hlqu3ft9wqcgkmun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVkc1ZkdEanZ0RE5LcU9R
            S2ZhMHk2dFNzVWNtTGpkUk00dXo4VEc3ejFvCmVZZlMzNXQ0UzhPS21LVTFZVTJN
            bERhWXBSZXR4azJnSDhXSFlzQUVmZk0KLS0tIHZLMCtsYk1Cc3N1VTBFdTQva08y
            bkNNbkwya3hJd2JodDdqOStPaG9Md0UKioBcL0Yh0pny768wl4bvKZPGq8oOqpTP
            aFvGvxVOtWDb6Bk9pLZbyv3qun4MIlFtqVX6dMq0O2Cm+8k62G2+Jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T17:16:47Z"
    mac: ENC[AES256_GCM,data:dR8sStsF3S5z5L6Vl3QF/kEjmnAbFEckaZs88Kj3AaT/ej18mjfNj3qDVLqg/wwiFZ8AnHHtppyEQOa7ttekHDIoZe1ckETy295Ix08WlaSeBtBkEfUHVDq6rdr7ruyf3bNOFe21B99NQP9Vv8Y8qlIRD3s272alx/NAyGLLGUw=,iv:EQHBtEB2BCaa7w9opUIeZTy4a+wSPTl737fmqLxK3Ho=,tag:6mJn382/9rH4uJoPBZ8AmQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
