apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: pipeline-gitops
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/tiwari91/pipeline-gitops
  ref:
    branch: master
